apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "extension-traefik.fullname" . }}
  labels:
    {{- include "extension-traefik.labels" . | nindent 4 }}
rules:
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
