# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - crd/traefik.yaml
  - manager/deployment.yaml
  - manager/service.yaml
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml

patchesStrategicMerge:
  - traefik_patch.yaml

namespace: system
